// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJN0u2-oI-GQokDB_IVKQtWULctTSv6Zc',
    appId: '1:885073266866:web:83aed602005b304eed21ab',
    messagingSenderId: '885073266866',
    projectId: 'flutter-firebase-e8b4c',
    authDomain: 'flutter-firebase-e8b4c.firebaseapp.com',
    storageBucket: 'flutter-firebase-e8b4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm0F_jJeKMUcAJnbZ8KxyFKzKes2fAyEs',
    appId: '1:885073266866:android:9184a9ea4f9479f3ed21ab',
    messagingSenderId: '885073266866',
    projectId: 'flutter-firebase-e8b4c',
    storageBucket: 'flutter-firebase-e8b4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxcSYuwwP_keGKnXxcd_uA-NWTzAaSWmo',
    appId: '1:885073266866:ios:eec81c019c5f51a4ed21ab',
    messagingSenderId: '885073266866',
    projectId: 'flutter-firebase-e8b4c',
    storageBucket: 'flutter-firebase-e8b4c.appspot.com',
    iosClientId: '885073266866-jukgp8q7ess1f31782jvinitcmn4b3of.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxcSYuwwP_keGKnXxcd_uA-NWTzAaSWmo',
    appId: '1:885073266866:ios:eec81c019c5f51a4ed21ab',
    messagingSenderId: '885073266866',
    projectId: 'flutter-firebase-e8b4c',
    storageBucket: 'flutter-firebase-e8b4c.appspot.com',
    iosClientId: '885073266866-jukgp8q7ess1f31782jvinitcmn4b3of.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
